# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Chocofi'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left","corne_right"]'
